# Use root/example as user/password credentials
version: '3.8'

services:
  mysqldb:
    image: mysql
    ports:
    - 8001:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql
  
volumes:
  mysql:
  mysql_config:
